In [1]:
# Import the Pandas library


import sys

sys.path.append('../')

from models.tensorflow_model import TensorFlowModel

model = TensorFlowModel()
path = "../test_data/new_data.xlsx"

coded_df = model.process_excel(path)


print(coded_df.info())
coded_df

2024-08-17 19:58:41.918444: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-17 19:58:41.973653: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-17 19:58:41.974726: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-17 19:58:42.789088: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


((2, 381), (2, 381))
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   NAME                 760 non-null    object 
 1   date                 760 non-null    int64  
 2   color_and_value      760 non-null    object 
 3   name_code            760 non-null    int64  
 4   day_of_month         760 non-null    int32  
 5   day_of_week          760 non-null    int32  
 6   date_code            760 non-null    int64  
 7   day_of_year          760 non-null    int64  
 8   value                760 non-null    float64
 9   color                760 non-null    object 
 10  extra                760 non-null    float64
 11  color_code           760 non-null    int64  
 12  next_color_code      758 non-null    float64
 13  previous_color_code  758 non-null    float64
 14  color_binary         760 non-null    int64  
 15  next_color_binary  

NAME                 date             color_and_value  name_code  \
0    CJ1  1733702400000000000   0.42857 | FF0000 | 184733          1   
1    CJ2  1733702400000000000      0.0 | FF9900 | 1224919          2   
2    CJ1  1733961600000000000   0.28571 | D5A6BD | 167139          1   
3    CJ2  1733961600000000000  -0.1429 | 00FF00 | 1091707          2   
4    CJ1  1734048000000000000   0.28571 | FF9900 | 138497          1   
..   ...                  ...                         ...        ...   
755  CJ2  1716940800100000000  11.7143 | FFFF00 | 1117856          2   
756  CJ1  1717027200100000000    15.5714 | 00FF00 | 61845          1   
757  CJ2  1717027200100000000  11.5714 | FF9900 | 1280565          2   
758  CJ1  1717113600100000000    15.5714 | FFFF00 | 58560          1   
759  CJ2  1717113600100000000  11.4286 | 00FF00 | 1296267          2   

     day_of_month  day_of_week  date_code  day_of_year     value   color  \
0               9            0          0          344   0.42857  FF0000   
1               9            0          0          344   0.00000  FF9900   
2              12            3          1          347   0.28571  D5A6BD   
3              12            3          1          347  -0.14290  00FF00   
4              13            4          2          348   0.28571  FF9900   
..            ...          ...        ...          ...       ...     ...   
755            29            2        377          150  11.71430  FFFF00   
756            30            3        378          151  15.57140  00FF00   
757            30            3        378          151  11.57140  FF9900   
758            31            4        379          152  15.57140  FFFF00   
759            31            4        379          152  11.42860  00FF00   

         extra  color_code  next_color_code  previous_color_code  \
0     184733.0           0              2.0                  NaN   
1    1224919.0           1              3.0                  NaN   
2     167139.0           2              1.0                  0.0   
3    1091707.0           3              1.0                  1.0   
4     138497.0           1              0.0                  2.0   
..         ...         ...              ...                  ...   
755  1117856.0           4              1.0                  0.0   
756    61845.0           3              4.0                  3.0   
757  1280565.0           1              3.0                  4.0   
758    58560.0           4              NaN                  3.0   
759  1296267.0           3              NaN                  1.0   

     color_binary  next_color_binary  color_group  next_color_group  
0               1                0.0            1               6.0  
1               0                1.0            5               2.0  
2               0                0.0            6               5.0  
3               1                0.0            2               5.0  
4               0                1.0            5               1.0  
..            ...                ...          ...               ...  
755             1                0.0            3               5.0  
756             1                1.0            2               3.0  
757             0                1.0            5               2.0  
758             1                NaN            3               NaN  
759             1                NaN            2               NaN  

[760 rows x 18 columns]

In [2]:
coded_df[["date_code"  ,'name_code' , 'day_of_year', 'day_of_month', 'day_of_week' ,"color_code" , 'value' , 'color_group','extra',  'next_color_group' ]]

date_code  name_code  day_of_year  day_of_month  day_of_week  color_code  \
0            0          1          344             9            0           0   
1            0          2          344             9            0           1   
2            1          1          347            12            3           2   
3            1          2          347            12            3           3   
4            2          1          348            13            4           1   
..         ...        ...          ...           ...          ...         ...   
755        377          2          150            29            2           4   
756        378          1          151            30            3           3   
757        378          2          151            30            3           1   
758        379          1          152            31            4           4   
759        379          2          152            31            4           3   

        value  color_group      extra  next_color_group  
0     0.42857            1   184733.0               6.0  
1     0.00000            5  1224919.0               2.0  
2     0.28571            6   167139.0               5.0  
3    -0.14290            2  1091707.0               5.0  
4     0.28571            5   138497.0               1.0  
..        ...          ...        ...               ...  
755  11.71430            3  1117856.0               5.0  
756  15.57140            2    61845.0               3.0  
757  11.57140            5  1280565.0               2.0  
758  15.57140            3    58560.0               NaN  
759  11.42860            2  1296267.0               NaN  

[760 rows x 10 columns]

In [3]:
from sklearn.model_selection import train_test_split

import pandas as pd

coded_df = coded_df.dropna(axis=0)


X = coded_df[["date_code"  ,'name_code' , 'day_of_year', 'day_of_month', 'day_of_week' ,"color_group" ,'extra', 'value']]


y = pd.get_dummies(coded_df['color_group']).astype(int)  # One-hot encode the target

y_labels = y.columns

y = y.values

print(X.shape)

print(y.shape)




(756, 8)
(756, 6)


In [4]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)


print(X.shape)

print(y.shape)




(756, 8)
(756, 6)


In [5]:
import numpy as np

def create_sequences(X,y, timesteps):
    sequences = []
    labels = []
    for i in range(len(X) - timesteps):
        sequences.append(X[i:i + timesteps])
        labels.append(y[i + timesteps])
    
    return np.array(sequences), np.array(labels)


timesteps =10

X , y = create_sequences(X,y, timesteps)


print(X.shape)
print(y.shape)







(746, 10, 8)
(746, 6)


In [6]:

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,shuffle=False)

# Normalize the feature data (optional but recommended for neural networks)


print(X.shape)
print(y.shape)



(746, 10, 8)
(746, 6)


In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization ,Flatten
# Define the input shape for LSTM

input_shape = (timesteps, X.shape[2])

model = Sequential([
    # Flatten the input before feeding into Dense layers
    Flatten(input_shape=input_shape),

    # First dense layer with Batch Normalization and Dropout
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),  # Dropout for regularization

    # Second dense layer with Batch Normalization and Dropout
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),  # Dropout for regularization

    # Third dense layer with Batch Normalization and Dropout
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),  # Dropout for regularization

    # Fourth dense layer with Batch Normalization and Dropout
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),  # Dropout for regularization

    # Output layer
    Dense(y_test.shape[1], activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [8]:
# Train the model
model.fit(X_train, y_train, epochs=60, batch_size=10, verbose=1)


Epoch 1/60
60/60 [==============================] - 2s 6ms/step - loss: 2.4759 - accuracy: 0.1829
Epoch 2/60
60/60 [==============================] - 0s 5ms/step - loss: 2.2846 - accuracy: 0.2265
Epoch 3/60
60/60 [==============================] - 0s 4ms/step - loss: 2.1266 - accuracy: 0.2064
Epoch 4/60
60/60 [==============================] - 0s 4ms/step - loss: 2.0472 - accuracy: 0.2299
Epoch 5/60
60/60 [==============================] - 0s 4ms/step - loss: 2.0204 - accuracy: 0.2349
Epoch 6/60
60/60 [==============================] - 0s 4ms/step - loss: 1.9143 - accuracy: 0.2500
Epoch 7/60
60/60 [==============================] - 0s 4ms/step - loss: 1.8381 - accuracy: 0.2483
Epoch 8/60
60/60 [==============================] - 0s 4ms/step - loss: 1.8386 - accuracy: 0.2567
Epoch 9/60
60/60 [==============================] - 0s 4ms/step - loss: 1.8597 - accuracy: 0.2500
Epoch 10/60
60/60 [==============================] - 0s 5ms/step - loss: 1.7834 - accuracy: 0.2617
Epoch 11/60
60/60 [

In [9]:
# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy}')


5/5 [==============================] - 0s 3ms/step - loss: 2.0211 - accuracy: 0.1933
Test Accuracy: 0.19333332777023315


In [10]:
# Make predictions
predictions = model.predict(X_test)


print(y_test)
print(predictions)


5/5 [==============================] - 0s 2ms/step
[[0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 

In [11]:
import numpy as np

def convert_to_labels(y_labels, arr):
   
    # Convert predictions to class indices
    classes = np.argmax(arr, axis=1)
    
    labels =   [y_labels[i] for i in classes]
    
    return labels


predictions_labels = convert_to_labels(y_labels , predictions)
y_test_labels = convert_to_labels(y_labels, y_test)

print(y_test_labels)
print(predictions_labels)


[5, 4, 6, 6, 1, 1, 3, 6, 5, 1, 6, 2, 3, 4, 6, 1, 4, 1, 6, 6, 1, 4, 6, 6, 2, 5, 6, 6, 4, 5, 1, 6, 3, 5, 1, 1, 1, 3, 6, 6, 5, 2, 1, 1, 4, 1, 1, 1, 2, 4, 3, 6, 1, 2, 6, 1, 1, 5, 6, 6, 4, 4, 6, 6, 5, 4, 6, 2, 4, 2, 1, 3, 4, 5, 3, 6, 3, 2, 2, 2, 4, 5, 2, 2, 1, 3, 3, 6, 5, 5, 6, 6, 1, 2, 3, 3, 1, 5, 6, 6, 1, 4, 3, 6, 3, 3, 2, 6, 1, 2, 2, 6, 1, 5, 3, 1, 2, 1, 1, 6, 3, 5, 6, 2, 2, 4, 2, 6, 5, 3, 1, 6, 4, 4, 3, 2, 1, 2, 6, 3, 5, 1, 1, 6, 5, 1, 2, 3, 2, 5]
[6, 1, 6, 1, 1, 1, 1, 1, 2, 3, 6, 6, 6, 1, 2, 1, 2, 1, 6, 1, 2, 1, 2, 1, 2, 1, 6, 1, 2, 1, 6, 1, 2, 1, 2, 1, 6, 1, 2, 3, 6, 1, 2, 1, 2, 2, 2, 3, 2, 3, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 3, 2, 3, 2, 2, 2, 1, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 1, 2, 3, 2, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2]


In [14]:
def make_pair(arr):
    if len(arr) % 2 == 0:
        arr = arr
    else:
        arr = arr[1:] 
    return arr

pr = make_pair(predictions_labels)
real = make_pair(y_test_labels)


pr_cj = []
real_cj = []

for i in range(len(pr)):
    if i % 2 == 0:
        pr_cj.append(pr[i])
        real_cj.append(real[i])

print(real_cj)
print(pr_cj)


[5, 6, 1, 3, 5, 6, 3, 6, 4, 6, 1, 6, 2, 6, 4, 1, 3, 1, 1, 6, 5, 1, 4, 1, 2, 3, 1, 6, 1, 6, 4, 6, 5, 6, 4, 1, 4, 3, 3, 2, 4, 2, 1, 3, 5, 6, 1, 3, 1, 6, 1, 3, 3, 2, 1, 2, 1, 3, 2, 1, 3, 6, 2, 2, 5, 1, 4, 3, 1, 6, 5, 1, 5, 2, 2]
[6, 6, 1, 1, 2, 6, 6, 2, 2, 6, 2, 2, 2, 6, 2, 6, 2, 2, 6, 2, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [13]:

def calculate_accuracy(arr1, arr2):
    gr1 = [2,3, 1]
    gr2 = [4,5,6]
    if len(arr1) != len(arr2):
        raise ValueError("Arrays must have the same length")
    
    arr1 = list(map(int, arr1))
    arr2 = list(map(int, arr2))
    
    correct_predictions = sum((a in gr1 and b in  gr1) or (a in gr2 and b in  gr2) for a, b in zip(arr1, arr2))
    accuracy = correct_predictions / len(arr1)
    return accuracy



print("acc = ", calculate_accuracy(y_test_labels, predictions_labels))

acc =  0.5333333333333333
