In [1]:
# Import the Pandas library

import openpyxl
import io
import tempfile
import pandas as pd
import numpy as np
import sys

sys.path.append('../')

from models.random_forest import RandomForest

model = RandomForest()
path = "../.test_data/more_data.xlsx"

coded_df = model.process_excel(path)


print(coded_df.info())
coded_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46376 entries, 0 to 46375
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   NAME             46376 non-null  object 
 1   name_code        46376 non-null  int64  
 2   date             46376 non-null  int64  
 3   color_and_value  46376 non-null  object 
 4   value            46376 non-null  float64
 5   color            46376 non-null  object 
 6   color_code       46376 non-null  int64  
 7   next_color_code  46240 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 2.8+ MB
None


NAME  name_code  date    color_and_value     value   color  \
0        GJ1          0     1   -16.155 | 00FFFF -16.15500  FFFFFF   
1        GJ2          1     1   -10.131 | 00FFFF -10.13100  FFFFFF   
2        GJ3          2     1     6.719 | 00FF00   6.71900  FFFFFF   
3        GJ4          3     1       8.2 | 00FFFF   8.20000  FFFFFF   
4        GJ5          4     1    -7.444 | 00FF00  -7.44400  FFFFFF   
...      ...        ...   ...                ...       ...     ...   
46371  GJ132        131   341  19.17218 | A9D08E  19.17218  FFFFFF   
46372  GJ133        132   341  -27.1069 | FFFF00 -27.10690  FFFFFF   
46373  GJ134        133   341  14.05361 | FFC000  14.05361  FFFFFF   
46374  GJ135        134   341  -5.21327 | FFFF00  -5.21327  FFFFFF   
46375  GJ136        135   341  51.27713 | A9D08E  51.27713  FFFFFF   

       color_code  next_color_code  
0               0              0.0  
1               0              1.0  
2               0              0.0  
3               0              0.0  
4               0              0.0  
...           ...              ...  
46371           0              NaN  
46372           0              NaN  
46373           0              NaN  
46374           0              NaN  
46375           0              NaN  

[46376 rows x 8 columns]

In [2]:
model.color_mapping


{0: 'FFFFFF', 1: 'FF9900', 2: 'D5A6BD'}

In [3]:
coded_df[ coded_df['color'] == 'D5A6BD']
# 46376    484 purple    2382 orange

NAME  name_code  date    color_and_value     value   color  \
109    GJ110        109     1    28.215 | D5A6BD  28.21500  D5A6BD   
142      GJ7          6     2    28.224 | D5A6BD  28.22400  D5A6BD   
178     GJ43         42     2    27.783 | D5A6BD  27.78300  D5A6BD   
205     GJ70         69     2    39.253 | D5A6BD  39.25300  D5A6BD   
209     GJ74         73     2    24.804 | D5A6BD  24.80400  D5A6BD   
...      ...        ...   ...                ...       ...     ...   
46269   GJ30         29   341  31.96514 | D5A6BD  31.96514  D5A6BD   
46297   GJ58         57   341  11.90044 | D5A6BD  11.90044  D5A6BD   
46320   GJ81         80   341  33.65664 | D5A6BD  33.65664  D5A6BD   
46333   GJ94         93   341  53.19525 | D5A6BD  53.19525  D5A6BD   
46347  GJ108        107   341  55.48429 | D5A6BD  55.48429  D5A6BD   

       color_code  next_color_code  
109             2              0.0  
142             2              0.0  
178             2              0.0  
205             2              2.0  
209             2              1.0  
...           ...              ...  
46269           2              NaN  
46297           2              NaN  
46320           2              NaN  
46333           2              NaN  
46347           2              NaN  

[2382 rows x 8 columns]

In [4]:
model.last_df

NAME 2024-04-24 00:00:00.1
0      GJ1     2.166186 | FFFF00
1      GJ2     3.942408 | FFFF00
2      GJ3     5.464429 | A9D08E
3      GJ4     1.083493 | FFFF00
4      GJ5     14.56136 | A9D08E
..     ...                   ...
131  GJ132     19.17218 | A9D08E
132  GJ133     -27.1069 | FFFF00
133  GJ134     14.05361 | FFC000
134  GJ135     -5.21327 | FFFF00
135  GJ136     51.27713 | A9D08E

[136 rows x 2 columns]

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split



# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = model.train_test_split(coded_df)


print(X_train.shape)
print(y_train.shape)

(36992, 4)
(36992, 3)


In [6]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Assuming X_train and y_train are already defined with shapes ((36992, 4), (36992, 10))
# If y_train is one-hot encoded, convert it to single integer labels
if len(y_train.shape) > 1 and y_train.shape[1] > 1:
    y_train_labels = np.argmax(y_train, axis=1)
else:
    y_train_labels = y_train


if len(y_test.shape) > 1 and y_test.shape[1] > 1:
    y_test_labels = np.argmax(y_test, axis=1)
else:
    y_test_labels = y_test


y_train_labels





array([0, 0, 0, ..., 0, 1, 0])

In [7]:
# Initialize the Random Forest classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier using the training data
classifier.fit(X_train, y_train_labels)

# As we are not splitting the dataset, we won’t be able to calculate validation accuracy.
# The model's training accuracy is usually not a good indicator of its ability to generalize.
print("Training complete. Random Forest model is trained on the entire dataset.")

# To get insights on feature importances provided by the classifier
feature_importances = classifier.feature_importances_
print("Feature Importances:", feature_importances)

# Reminder: To evaluate the model's performance, you would typically use a portion of your data as a test set.

Training complete. Random Forest model is trained on the entire dataset.
Feature Importances: [0.30543619 0.26696274 0.41513001 0.01247106]


In [8]:
from sklearn.metrics import mean_squared_error, accuracy_score

# Assuming your classifier has been trained with X_train and y_train_labels

# Making predictions for the training set
y_pred = classifier.predict(X_test)  # For accuracy
y_pred_proba = classifier.predict_proba(X_test)  # For MSE





In [9]:
y_test_labels
np.unique(y_test_labels, return_counts=True)

(array([0, 1, 2]), array([8673,   95,  480]))

In [10]:
y_pred
np.unique(y_pred, return_counts=True)

(array([0, 1, 2]), array([9124,   61,   63]))

In [11]:
# Computing the accuracy for the training set
accuracy = accuracy_score(y_test_labels, y_pred)
print(f"Training Accuracy: {accuracy * 100:.2f}%")

# If y_train was one-hot encoded, we can calculate MSE using the predicted probabilities


Training Accuracy: 93.85%


In [13]:

preferred_correct_predictions = 0
c1= 0
c2 = 0

color_code = [1,2]
for t, p in zip(y_test_labels, y_pred):
    # If the predicted color is not in the allowed values, count it (regardless of it being correct)
    # OR
    # If the predicted color is an allowed value and matches the true color, count it
    if  (p in color_code and t == p):
        preferred_correct_predictions += 1
    if t in color_code:
        c1 += 1
    if p in  color_code :
        c2 += 1

    preferred_accuracy = (preferred_correct_predictions / len(y_pred))

preferred_correct_predictions , c2 , c1  , len(y_pred)

(64, 124, 575, 9248)