In [1]:
# Import the Pandas library

import openpyxl
import io
import tempfile
import pandas as pd
import numpy as np
import sys

sys.path.append('../')

from models.tensorflow_model import TensoFlowModel

model = TensoFlowModel()
path = "../.test_data/dataprocess.xlsx"

coded_df = model.process_excel(path)


print(coded_df.info())
coded_df

2024-04-28 16:51:00.033069: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-28 16:51:00.036868: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-28 16:51:00.115582: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-28 16:51:01.133007: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   NAME             3024 non-null   object 
 1   name_code        3024 non-null   int64  
 2   date             3024 non-null   int64  
 3   color_and_value  3024 non-null   object 
 4   value            3024 non-null   float64
 5   color            3024 non-null   object 
 6   color_code       3024 non-null   int64  
 7   next_color_code  3015 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 189.1+ KB
None


NAME  name_code  date    color_and_value     value   color  color_code  \
0     GJ1          0     1   -16.155 | 00FFFF -16.15500  00FFFF           0   
1     GJ2          1     1   -10.131 | 00FFFF -10.13100  00FFFF           0   
2     GJ3          2     1     6.719 | 00FF00   6.71900  00FF00           1   
3     GJ4          3     1       8.2 | 00FFFF   8.20000  00FFFF           0   
4     GJ5          4     1    -7.444 | 00FF00  -7.44400  00FF00           1   
...   ...        ...   ...                ...       ...     ...         ...   
3019  GJ5          4   336  -3.38613 | 8EA9DB  -3.38613  8EA9DB           8   
3020  GJ6          5   336  -9.74303 | FFFF00  -9.74303  FFFF00           3   
3021  GJ7          6   336  -10.9962 | A9D08E -10.99620  A9D08E           5   
3022  GJ8          7   336  16.04017 | FFC000  16.04017  FFC000           7   
3023  GJ9          8   336  -5.71004 | 8EA9DB  -5.71004  8EA9DB           8   

      next_color_code  
0                 3.0  
1                 2.0  
2                 3.0  
3                 3.0  
4                 1.0  
...               ...  
3019              NaN  
3020              NaN  
3021              NaN  
3022              NaN  
3023              NaN  

[3024 rows x 8 columns]

In [2]:
model.color_mapping



{0: '00FFFF',
 1: '00FF00',
 2: 'FF9900',
 3: 'FFFF00',
 4: 'D5A6BD',
 5: 'A9D08E',
 6: '9BC2E6',
 7: 'FFC000',
 8: '8EA9DB',
 9: 'FF0000'}

In [3]:
model.last_df

NAME 2024-04-16 00:00:00
0  GJ1   -19.8579 | FFFF00
1  GJ2   -10.1783 | FFFF00
2  GJ3   -7.68448 | FFFF00
3  GJ4   -12.2896 | 8EA9DB
4  GJ5   -3.38613 | 8EA9DB
5  GJ6   -9.74303 | FFFF00
6  GJ7   -10.9962 | A9D08E
7  GJ8   16.04017 | FFC000
8  GJ9   -5.71004 | 8EA9DB

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split



# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = model.train_test_split(coded_df)


X_train.shape , y_train.shape

((2412, 4, 1), (2412, 10))

In [5]:

model.fit(X_train, X_test, y_train, y_test)

print(f'mse : {model.mse}' )

print(f'accuracy_percentage : {model.accuracy_percentage}' )

/home/adil/repo/predict_sphere/venv/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.1232 - loss: 3.3465
Epoch 2/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.1712 - loss: 2.6732
Epoch 3/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.2096 - loss: 2.3749
Epoch 4/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.2502 - loss: 2.1607
Epoch 5/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.2556 - loss: 2.0195
Epoch 6/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.2600 - loss: 1.9205
Epoch 7/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.2587 - loss: 1.8508
Epoch 8/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.2568 - loss: 1.7889
Epoch 9/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2783 - loss: 1.7140
Epoch 10/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.2870 - loss: 1.7222
Epoch 11/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.2831 - loss: 1.6770
Epoch 12/40
76/76 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy:

In [7]:

model.predict()



[[ 3.350000e+02  0.000000e+00 -6.117060e+00  5.000000e+00]
 [ 3.350000e+02  1.000000e+00 -4.223000e-02  8.000000e+00]
 [ 3.350000e+02  2.000000e+00 -2.247540e+00  7.000000e+00]
 [ 3.350000e+02  3.000000e+00 -5.760870e+00  8.000000e+00]
 [ 3.350000e+02  4.000000e+00 -3.523970e+00  5.000000e+00]
 [ 3.350000e+02  5.000000e+00  1.737010e+01  5.000000e+00]
 [ 3.350000e+02  6.000000e+00 -5.552280e+00  5.000000e+00]
 [ 3.350000e+02  7.000000e+00  1.154082e+01  7.000000e+00]
 [ 3.350000e+02  8.000000e+00 -8.951480e+00  7.000000e+00]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[3.7510262e-04 3.4490981e-04 4.4492655e-04 2.3192491e-01 4.5265824e-02
  2.8099209e-01 2.0065689e-03 1.7230421e-01 2.6605940e-01 2.8204813e-04]
 [3.4618354e-04 2.7295729e-04 3.3556539e-04 1.9959140e-01 5.5381697e-02
  2.8906381e-01 1.8882926e-03 1.7225683e-01 2.8036866e-01 4.9470580e-04]
 [3.0862683e-04 2.4980889e-04 3.1378926e-04 1.9905186e-01 5.4064237e-02
  2.8637099e-01 1.5799410e-03 1.7528044e-01 2.8234881e-01 4.3162736e

NAME 2024-04-16 00:00:00  next_color_code next_color
0  GJ1   -19.8579 | FFFF00                5     A9D08E
1  GJ2   -10.1783 | FFFF00                5     A9D08E
2  GJ3   -7.68448 | FFFF00                5     A9D08E
3  GJ4   -12.2896 | 8EA9DB                8     8EA9DB
4  GJ5   -3.38613 | 8EA9DB                8     8EA9DB
5  GJ6   -9.74303 | FFFF00                8     8EA9DB
6  GJ7   -10.9962 | A9D08E                8     8EA9DB
7  GJ8   16.04017 | FFC000                8     8EA9DB
8  GJ9   -5.71004 | 8EA9DB                8     8EA9DB