In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


2024-04-28 14:47:33.692997: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-28 14:47:33.699698: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-28 14:47:33.791638: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-28 14:47:34.795259: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [11]:
# Load the Iris dataset
iris = datasets.load_iris()
X, y_brut = iris.data, iris.target

# Convert labels to one-hot encoding
encoder = OneHotEncoder()
y = encoder.fit_transform(y_brut.reshape(-1, 1)).toarray()

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [12]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
# Initialize a Sequential model
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)), # Input layer with 4 features and a hidden layer with 10 neurons
    Dense(3, activation='softmax') # Output layer with 3 neurons representing the 3 classes
])


model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()


/home/adil/repo/predict_sphere/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83 (332.00 B)

 Trainable params: 83 (332.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
history = model.fit(
    X_train, 
    y_train, 
    epochs=100,
    batch_size=5,
    validation_data=(X_test, y_test)
)
loss, accuracy = model.evaluate(X_test, y_test)
print("Test accuracy:", accuracy)


Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3815 - loss: 1.0142 - val_accuracy: 0.3000 - val_loss: 0.9992
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3598 - loss: 0.9643 - val_accuracy: 0.3000 - val_loss: 0.9389
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3410 - loss: 0.9405 - val_accuracy: 0.5667 - val_loss: 0.9162
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4817 - loss: 0.9147 - val_accuracy: 0.4000 - val_loss: 0.8948
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4104 - loss: 0.9148 - val_accuracy: 0.4667 - val_loss: 0.8798
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5467 - loss: 0.8985 - val_accuracy: 0.6333 - val_loss: 0.8659
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6427 - loss: 0.8622 - val_accuracy: 0.6667 - val_loss: 0.8500
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6842 - loss: 0.8450 - val_accuracy: 0.8000 - v

In [15]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test accuracy:", accuracy)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2750
Test accuracy: 1.0


In [16]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [17]:
# Make predictions on the test set using the trained model
predictions = model.predict(X_test)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step


array([[5.6759147e-03, 6.5554339e-01, 3.3878079e-01],
       [9.8033643e-01, 1.9386085e-02, 2.7739728e-04],
       [2.5336569e-06, 1.4159745e-01, 8.5840005e-01],
       [6.7418166e-03, 5.8247715e-01, 4.1078100e-01],
       [3.2391022e-03, 6.5544492e-01, 3.4131598e-01],
       [9.7205776e-01, 2.7427478e-02, 5.1468186e-04],
       [6.1864495e-02, 6.9981325e-01, 2.3832232e-01],
       [6.3191861e-04, 3.2938993e-01, 6.6997820e-01],
       [1.3704876e-03, 5.3101176e-01, 4.6761781e-01],
       [2.5059916e-02, 7.1739036e-01, 2.5754970e-01],
       [1.4088691e-03, 3.9529386e-01, 6.0329723e-01],
       [9.5240360e-01, 4.6545450e-02, 1.0510229e-03],
       [9.7229820e-01, 2.7236048e-02, 4.6575046e-04],
       [9.5629382e-01, 4.2814404e-02, 8.9183060e-04],
       [9.8455429e-01, 1.5147658e-02, 2.9815122e-04],
       [9.0366863e-03, 5.9315068e-01, 3.9781266e-01],
       [1.0488803e-04, 2.1268500e-01, 7.8721005e-01],
       [1.9105919e-02, 7.1269393e-01, 2.6820016e-01],
       [7.5361743e-03, 6.051

In [19]:
import numpy as np 
predicted_class_indices = np.argmax(predictions, axis=1)
true_labels = np.argmax(y_test, axis=1)




array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [20]:
predicted_class_indices

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [21]:
true_labels

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [24]:
one_hot_predictions = np.zeros((predictions.shape[0], len(encoder.categories_[0])))

# Set the predicted labels to 1
for i, label in enumerate(predicted_class_indices):
    one_hot_predictions[i, label] = 1

# Step 2: Use the encoder to inverse transform the one-hot encoded predictions
y_test_pred = encoder.inverse_transform(one_hot_predictions)

y_test_pred

array([[1],
       [0],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [1],
       [1],
       [2],
       [0],
       [0],
       [0],
       [0],
       [1],
       [2],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0]])